[2025-01-23T13:15:07.681+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task45_train_models_v2.task234_training_models.taskRandomForestRegressor manual__2025-01-23T13:14:50.410181+00:00 [queued]>
[2025-01-23T13:15:07.783+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task45_train_models_v2.task234_training_models.taskRandomForestRegressor manual__2025-01-23T13:14:50.410181+00:00 [queued]>
[2025-01-23T13:15:07.783+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-23T13:15:07.931+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task234_training_models.taskRandomForestRegressor> on 2025-01-23 13:14:50.410181+00:00
[2025-01-23T13:15:07.987+0000] {standard_task_runner.py:60} INFO - Started process 7393 to run task
[2025-01-23T13:15:08.005+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task45_train_models_v2', 'task234_training_models.taskRandomForestRegressor', 'manual__2025-01-23T13:14:50.410181+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/task45_train_models_v2.py', '--cfg-path', '/tmp/tmpezn3glnh']
[2025-01-23T13:15:08.026+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask task234_training_models.taskRandomForestRegressor
[2025-01-23T13:15:08.128+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-23T13:15:08.356+0000] {task_command.py:423} INFO - Running <TaskInstance: task45_train_models_v2.task234_training_models.taskRandomForestRegressor manual__2025-01-23T13:14:50.410181+00:00 [running]> on host a8cdec4ae828
[2025-01-23T13:15:08.904+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task45_train_models_v2' AIRFLOW_CTX_TASK_ID='task234_training_models.taskRandomForestRegressor' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T13:14:50.410181+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T13:14:50.410181+00:00'
[2025-01-23T13:15:09.570+0000] {xcom.py:664} ERROR - Object of type LinearRegression is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-01-23T13:15:09.589+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'sklearn.linear_model._base.LinearRegression'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task45_train_models_v2.py", line 81, in compute_model_score
    task_instance.xcom_push(key="model_name",value=model)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LinearRegression is not JSON serializable
[2025-01-23T13:15:09.616+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=task45_train_models_v2, task_id=task234_training_models.taskRandomForestRegressor, execution_date=20250123T131450, start_date=20250123T131507, end_date=20250123T131509
[2025-01-23T13:15:09.706+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task task234_training_models.taskRandomForestRegressor (Object of type LinearRegression is not JSON serializable; 7393)
[2025-01-23T13:15:09.790+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-23T13:15:09.853+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
