[2025-01-23T10:52:48.985+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipline.task1_retrieveData manual__2025-01-23T10:52:44.048326+00:00 [queued]>
[2025-01-23T10:52:49.012+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipline.task1_retrieveData manual__2025-01-23T10:52:44.048326+00:00 [queued]>
[2025-01-23T10:52:49.013+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-23T10:52:49.047+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task1_retrieveData> on 2025-01-23 10:52:44.048326+00:00
[2025-01-23T10:52:49.071+0000] {standard_task_runner.py:60} INFO - Started process 2746 to run task
[2025-01-23T10:52:49.079+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'full_pipline', 'task1_retrieveData', 'manual__2025-01-23T10:52:44.048326+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/allTasks_taskgroup.py', '--cfg-path', '/tmp/tmp911gn1_9']
[2025-01-23T10:52:49.088+0000] {standard_task_runner.py:88} INFO - Job 58: Subtask task1_retrieveData
[2025-01-23T10:52:49.114+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-23T10:52:49.189+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipline.task1_retrieveData manual__2025-01-23T10:52:44.048326+00:00 [running]> on host a8cdec4ae828
[2025-01-23T10:52:49.344+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_pipline' AIRFLOW_CTX_TASK_ID='task1_retrieveData' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T10:52:44.048326+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T10:52:44.048326+00:00'
[2025-01-23T10:52:49.921+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-23T10:52:49.940+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=full_pipline, task_id=task1_retrieveData, execution_date=20250123T105244, start_date=20250123T105248, end_date=20250123T105249
[2025-01-23T10:52:49.988+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-23T10:52:50.026+0000] {dagrun.py:822} ERROR - Failed to get task for ti <TaskInstance: full_pipline.task_23.task2_last20recodes manual__2025-01-23T10:52:44.048326+00:00 [None]>. Marking it as removed.
[2025-01-23T10:52:50.032+0000] {dagrun.py:822} ERROR - Failed to get task for ti <TaskInstance: full_pipline.task_23.task3_allrecodes manual__2025-01-23T10:52:44.048326+00:00 [None]>. Marking it as removed.
[2025-01-23T10:52:50.048+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
