[2025-01-23T13:29:17.610+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task45_train_models_v2.task5_selectBestModel manual__2025-01-23T13:28:57.803297+00:00 [queued]>
[2025-01-23T13:29:17.625+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task45_train_models_v2.task5_selectBestModel manual__2025-01-23T13:28:57.803297+00:00 [queued]>
[2025-01-23T13:29:17.625+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-23T13:29:17.656+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task5_selectBestModel> on 2025-01-23 13:28:57.803297+00:00
[2025-01-23T13:29:17.668+0000] {standard_task_runner.py:60} INFO - Started process 7936 to run task
[2025-01-23T13:29:17.677+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'task45_train_models_v2', 'task5_selectBestModel', 'manual__2025-01-23T13:28:57.803297+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/task45_train_models_v2.py', '--cfg-path', '/tmp/tmpvrx9qc5b']
[2025-01-23T13:29:17.679+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask task5_selectBestModel
[2025-01-23T13:29:17.697+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-23T13:29:17.744+0000] {task_command.py:423} INFO - Running <TaskInstance: task45_train_models_v2.task5_selectBestModel manual__2025-01-23T13:28:57.803297+00:00 [running]> on host a8cdec4ae828
[2025-01-23T13:29:17.922+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task45_train_models_v2' AIRFLOW_CTX_TASK_ID='task5_selectBestModel' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T13:28:57.803297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-23T13:28:57.803297+00:00'
[2025-01-23T13:29:18.039+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task45_train_models_v2.py", line 84, in select_bestModel
    clf = models[np.argmin(scores)]
  File "<__array_function__ internals>", line 200, in argmin
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1338, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[2025-01-23T13:29:18.054+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=task45_train_models_v2, task_id=task5_selectBestModel, execution_date=20250123T132857, start_date=20250123T132917, end_date=20250123T132918
[2025-01-23T13:29:18.081+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task task5_selectBestModel ('<' not supported between instances of 'NoneType' and 'NoneType'; 7936)
[2025-01-23T13:29:18.129+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-01-23T13:29:18.157+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
